version: "3.8"
services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
  php-apache:
    build:
      context: .
    depends_on:
      - "traefik"
      - "mysql"
    ports:
      - 8000:80
    volumes:
      - "./www:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`localhost`, `lvh.me`, `pmamp.lvh.me`, `127.0.0.1`)"
      - "traefik.http.routers.php-apache.entrypoints=web"

  mysql:
    platform: linux/x86_64
    image: "mysql:8.0.27"
    
    depends_on:
      - "traefik"
    volumes:
      - "./dbdata:/var/lib/mysql"
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - "mysql"
    links:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pma.localhost`, `pma.lvh.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
    name: "traefikNetwork"
